using System.Text.Json;
using System.Text.Json.Serialization;

namespace Smn.UiKit.Web.Infrastructure;

/// <summary>Entry of the <c>manifest.json</c> generated by Vite.</summary>
public sealed class ViteManifestEntry
{
    /// <summary>Final file name, including the content hash.</summary>
    [JsonPropertyName("file")]
    public string File { get; init; } = string.Empty;

    /// <summary>Stylesheets associated with the entry point.</summary>
    [JsonPropertyName("css")]
    public IReadOnlyList<string> Css { get; init; } = [];
}

/// <summary>Reads and caches the Vite manifest.</summary>
public sealed class ViteManifestReader
{
    private const string ManifestPath = "dist/.vite/manifest.json";

    private readonly IWebHostEnvironment _environment;
    private readonly Lazy<Dictionary<string, ViteManifestEntry>> _manifest;

    /// <summary>Creates the reader for the given hosting environment.</summary>
    public ViteManifestReader(IWebHostEnvironment environment)
    {
        _environment = environment;
        _manifest = new Lazy<Dictionary<string, ViteManifestEntry>>(Load);
    }

    /// <summary>Gets the manifest entry for the given source path.</summary>
    public ViteManifestEntry? GetEntry(string source)
    {
        return _manifest.Value.GetValueOrDefault(source);
    }

    private Dictionary<string, ViteManifestEntry> Load()
    {
        var path = Path.Combine(_environment.WebRootPath, ManifestPath);

        if (!File.Exists(path))
        {
            return [];
        }

        using var stream = File.OpenRead(path);

        return JsonSerializer.Deserialize<Dictionary<string, ViteManifestEntry>>(stream) ?? [];
    }
}
